### ISSUE TITLE
FileNotFoundError with eval_nn.py

### ISSUE THREAD

**Issue by andrewjong** [danlou/LMMS#2]
I get the following error when trying to run eval_nn. @danlou Can you help me understand what's missing, please? I don't see any mention of this file in the Readme.
```bash
$ python eval_nn.py -sv_path data/vectors/lmms_1024.bert-large-cased.npz -test_set ALL

01-Nov-19 11:57:26 - INFO - Loading SensesVSM ...
01-Nov-19 11:57:29 - INFO - Loaded SensesVSM
Traceback (most recent call last):
  File "eval_nn.py", line 169, in <module>
    with open(results_path, 'w') as results_f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/results/1572634649.ALL.mean.key
```
I opted to download the provided sense embeddings instead of creating my own.

**Comment by danlou** [comment]
Hi @andrewjong ,

I think that error is caused because there's no 'results' folder inside of the 'data' folder in this repository. Simply create that folder and it should work.

From the repository root, run:
`mkdir data/results
`

Just pushed a commit adding that folder and a readme.

Let me know if this solves your issue.

Best,
Daniel

**Comment by andrewjong** [comment]
Works great! Thanks Daniel.

Overall this is a very nice tool. Thank you for making it so modular! Definitely will cite your paper.
